/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PosRouteImport } from './routes/pos'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as InvoiceInvoiceIdRouteImport } from './routes/invoice.$invoiceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceInvoiceIdRoute = InvoiceInvoiceIdRouteImport.update({
  id: '/invoice/$invoiceId',
  path: '/invoice/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/invoice/$invoiceId': typeof InvoiceInvoiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/invoice/$invoiceId': typeof InvoiceInvoiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/invoice/$invoiceId': typeof InvoiceInvoiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inventory'
    | '/login'
    | '/pos'
    | '/purchases'
    | '/reports'
    | '/invoice/$invoiceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inventory'
    | '/login'
    | '/pos'
    | '/purchases'
    | '/reports'
    | '/invoice/$invoiceId'
  id:
    | '__root__'
    | '/'
    | '/inventory'
    | '/login'
    | '/pos'
    | '/purchases'
    | '/reports'
    | '/invoice/$invoiceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  PosRoute: typeof PosRoute
  PurchasesRoute: typeof PurchasesRoute
  ReportsRoute: typeof ReportsRoute
  InvoiceInvoiceIdRoute: typeof InvoiceInvoiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$invoiceId': {
      id: '/invoice/$invoiceId'
      path: '/invoice/$invoiceId'
      fullPath: '/invoice/$invoiceId'
      preLoaderRoute: typeof InvoiceInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  PosRoute: PosRoute,
  PurchasesRoute: PurchasesRoute,
  ReportsRoute: ReportsRoute,
  InvoiceInvoiceIdRoute: InvoiceInvoiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
